require('dotenv').config();
const express=require('express'),path=require('path'),fs=require('fs'),crypto=require('crypto'),multer=require('multer'),Database=require('better-sqlite3'),helmet=require('helmet'),rateLimit=require('express-rate-limit');
const app=express(),PORT=Number(process.env.PORT||3000),uploadDir=path.join(__dirname,'public','uploads');
fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(path.join(__dirname,'quickmart.db'));
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT DEFAULT '',price REAL NOT NULL CHECK(price>=0),stock INTEGER DEFAULT 0 CHECK(stock>=0),image TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,email TEXT NOT NULL,total REAL NOT NULL,status TEXT DEFAULT 'Awaiting Payment',razorpay_order_id TEXT,razorpay_payment_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,product_name TEXT NOT NULL,price REAL NOT NULL,quantity INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,email TEXT NOT NULL,subject TEXT NOT NULL,status TEXT DEFAULT 'Open',token TEXT UNIQUE NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id INTEGER NOT NULL,sender TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS webhook_events(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT UNIQUE NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`);
try{db.exec('ALTER TABLE orders ADD COLUMN quantity INTEGER DEFAULT 1')}catch(e){}
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(r,f,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(6).toString('hex')+path.extname(f.originalname).toLowerCase())}),limits:{fileSize:5*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(f.mimetype))});
const apiLimiter=rateLimit({windowMs:15*60*1000,max:180,standardHeaders:'draft-7',legacyHeaders:false});
const paymentLimiter=rateLimit({windowMs:15*60*1000,max:30,message:{error:'Too many payment attempts. Please try again later.'}});
app.disable('x-powered-by');app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use('/api',apiLimiter);
app.use(express.json({limit:'100kb'}));app.use(express.urlencoded({extended:true,limit:'100kb'}));app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
function safeEqual(a,b){const A=Buffer.from(String(a||'')),B=Buffer.from(String(b||''));return A.length===B.length&&crypto.timingSafeEqual(A,B)}
function admin(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Basic ')){res.set('WWW-Authenticate','Basic realm="Quick Mart Admin"');return res.status(401).send('Admin login required')}let raw;try{raw=Buffer.from(h.slice(6),'base64').toString('utf8')}catch{return res.status(401).send('Invalid credentials')}const i=raw.indexOf(':');const u=i>=0?raw.slice(0,i):raw,p=i>=0?raw.slice(i+1):'';if(!process.env.ADMIN_USER||!process.env.ADMIN_PASSWORD||!safeEqual(u,process.env.ADMIN_USER)||!safeEqual(p,process.env.ADMIN_PASSWORD))return res.status(403).send('Wrong admin credentials');next()}
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function cleanInt(v,min=0,max=100000){const n=Number(v);return Number.isInteger(n)&&n>=min&&n<=max?n:null}
function cleanPrice(v){const n=Number(v);return Number.isFinite(n)&&n>=0&&n<=10000000?Math.round(n*100)/100:null}
function token(){return crypto.randomBytes(32).toString('hex')}
function razorpayConfigured(){return !!(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET)}
async function discord(text){if(!process.env.DISCORD_WEBHOOK_URL)return;try{await fetch(process.env.DISCORD_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content:String(text).slice(0,1900)})})}catch(e){console.error('Discord:',e.message)}}
async function createRazorpayOrder(amount,receipt){const auth=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64');const r=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json'},body:JSON.stringify({amount:Math.round(amount*100),currency:'INR',receipt:String(receipt)})});const d=await r.json();if(!r.ok)throw new Error(d.error?.description||'Razorpay order creation failed');return d}
function verifyPaymentSignature(orderId,paymentId,signature){const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${orderId}|${paymentId}`).digest('hex');return safeEqual(expected,signature)}
async function fetchPayment(paymentId){const auth=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64');const r=await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Basic ${auth}`}});const d=await r.json();if(!r.ok)throw new Error(d.error?.description||'Unable to verify payment');return d}
function orderItems(orderId){let items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(orderId);if(!items.length){const o=db.prepare('SELECT o.*,p.name product_name,p.price FROM orders o JOIN products p ON p.id=o.product_id WHERE o.id=?').get(orderId);if(o)items=[{product_id:o.product_id,product_name:o.product_name,price:o.price,quantity:o.quantity||1}]}return items}
async function markPaid(rorder,paymentId){const order=db.prepare('SELECT * FROM orders WHERE razorpay_order_id=?').get(rorder);if(!order)return false;if(order.status==='Paid')return true;const items=orderItems(order.id);const tx=db.transaction(()=>{for(const item of items){const changed=db.prepare('UPDATE products SET stock=stock-? WHERE id=? AND stock>=?').run(item.quantity,item.product_id,item.quantity);if(!changed.changes)throw new Error(`Stock is no longer available for ${item.product_name}`)}db.prepare("UPDATE orders SET status='Paid',razorpay_payment_id=? WHERE id=?").run(paymentId||null,order.id);const t=token();const subject=`Order #${order.id} — ${items.map(x=>x.product_name).join(', ')}`;const tic=db.prepare('INSERT INTO tickets(order_id,email,subject,token) VALUES(?,?,?,?)').run(order.id,order.email,subject,t);db.prepare('INSERT INTO messages(ticket_id,sender,message) VALUES(?,?,?)').run(tic.lastInsertRowid,'system',`Payment received successfully. Order #${order.id}. Total ₹${Number(order.total).toFixed(2)}.`);return t});try{const t=tx();await discord(`✅ **Quick M@rt Payment Received — Order #${order.id}**\nTotal: ₹${Number(order.total).toFixed(2)}\nCustomer: ${order.email}\n🎫 /ticket/${t}`);return t}catch(e){console.error('markPaid:',e.message);throw e}}

app.post('/api/razorpay/webhook',express.raw({type:'application/json'}),async(req,res)=>{try{const secret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!secret)return res.status(503).send('Webhook secret not configured');const signature=req.headers['x-razorpay-signature']||'';const expected=crypto.createHmac('sha256',secret).update(req.body).digest('hex');if(!safeEqual(expected,signature))return res.status(400).send('Invalid signature');const event=JSON.parse(req.body.toString('utf8'));const eventId=event.id||crypto.createHash('sha256').update(req.body).digest('hex');try{db.prepare('INSERT INTO webhook_events(event_id) VALUES(?)').run(eventId)}catch(e){if(String(e.message).includes('UNIQUE'))return res.json({ok:true,duplicate:true});throw e}if(event.event==='payment.captured'||event.event==='order.paid'){const payment=event.payload?.payment?.entity;const rorder=payment?.order_id||event.payload?.order?.entity?.id;if(rorder)await markPaid(rorder,payment?.id)}else if(event.event==='payment.failed'){const payment=event.payload?.payment?.entity;if(payment?.order_id)db.prepare("UPDATE orders SET status='Payment Failed' WHERE razorpay_order_id=? AND status!='Paid'").run(payment.order_id)}res.json({ok:true})}catch(e){console.error('Webhook:',e);res.status(500).send('Webhook error')}});

app.get('/api/products',(q,s)=>s.json(db.prepare('SELECT * FROM products ORDER BY id DESC').all()));
app.post('/api/products',admin,upload.single('image'),(q,s)=>{try{let{name,description='',price,stock=0}=q.body;const pr=cleanPrice(price),st=cleanInt(stock,0,1000000);name=String(name||'').trim();if(!name||name.length>120||pr===null||st===null)return s.status(400).json({error:'Invalid product data'});const image=q.file?'/uploads/'+q.file.filename:'';const x=db.prepare('INSERT INTO products(name,description,price,stock,image) VALUES(?,?,?,?,?)').run(name,String(description).slice(0,2000),pr,st,image);s.json({ok:true,id:x.lastInsertRowid})}catch(e){s.status(400).json({error:'Invalid image or product data'})}});
app.put('/api/products/:id',admin,upload.single('image'),(q,s)=>{try{const id=cleanInt(q.params.id,1),old=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!old)return s.status(404).json({error:'Product not found'});const pr=cleanPrice(q.body.price),st=cleanInt(q.body.stock,0,1000000),name=String(q.body.name||'').trim();if(!name||name.length>120||pr===null||st===null)return s.status(400).json({error:'Invalid product data'});const image=q.file?'/uploads/'+q.file.filename:old.image;db.prepare('UPDATE products SET name=?,description=?,price=?,stock=?,image=? WHERE id=?').run(name,String(q.body.description||'').slice(0,2000),pr,st,image,id);s.json({ok:true})}catch(e){s.status(400).json({error:'Invalid product data'})}});
app.delete('/api/products/:id',admin,(q,s)=>{const id=cleanInt(q.params.id,1);db.prepare('DELETE FROM products WHERE id=?').run(id);s.json({ok:true})});

app.post('/api/orders',async(q,s)=>{try{const email=String(q.body.email||'').trim();let items=Array.isArray(q.body.items)?q.body.items:[];if(!items.length&&q.body.productId)items=[{productId:q.body.productId,quantity:q.body.quantity||1}];if(!validEmail(email)||!items.length)return s.status(400).json({error:'Valid email and cart items are required'});const normalized=[];for(const raw of items){const productId=cleanInt(raw.productId,1),quantity=cleanInt(raw.quantity,1,1000);if(!productId||!quantity)return s.status(400).json({error:'Invalid cart item'});const p=db.prepare('SELECT * FROM products WHERE id=?').get(productId);if(!p)return s.status(404).json({error:'Product not found'});if(p.stock<quantity)return s.status(400).json({error:`Not enough stock for ${p.name}`});normalized.push({p,quantity})}if(!razorpayConfigured())return s.status(503).json({error:'Razorpay is not configured. Add your server-side Razorpay keys.'});const total=Math.round(normalized.reduce((sum,x)=>sum+x.p.price*x.quantity,0)*100)/100;const tx=db.transaction(()=>{const ord=db.prepare("INSERT INTO orders(product_id,email,total,status,quantity) VALUES(?,?,?,?,?)").run(normalized[0].p.id,email,total,'Awaiting Payment',normalized.reduce((n,x)=>n+x.quantity,0));for(const x of normalized)db.prepare('INSERT INTO order_items(order_id,product_id,product_name,price,quantity) VALUES(?,?,?,?,?)').run(ord.lastInsertRowid,x.p.id,x.p.name,x.p.price,x.quantity);return ord.lastInsertRowid});const localId=tx();let rz;try{rz=await createRazorpayOrder(total,`qm-${localId}`)}catch(e){db.prepare("UPDATE orders SET status='Payment Setup Failed' WHERE id=?").run(localId);throw e}db.prepare('UPDATE orders SET razorpay_order_id=? WHERE id=?').run(rz.id,localId);s.json({ok:true,orderId:localId,razorpay:{keyId:process.env.RAZORPAY_KEY_ID,orderId:rz.id,amount:rz.amount,currency:rz.currency,name:'Quick M@rt',description:normalized.map(x=>`${x.p.name} × ${x.quantity}`).join(', '),prefill:{email}}})}catch(e){console.error('Order:',e.message);s.status(500).json({error:e.message||'Unable to create payment'})}});
app.post('/api/payments/verify',paymentLimiter,async(q,s)=>{try{const{localOrderId,razorpay_order_id,razorpay_payment_id,razorpay_signature}=q.body;const id=cleanInt(localOrderId,1),o=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o||o.razorpay_order_id!==razorpay_order_id)return s.status(400).json({error:'Order mismatch'});if(o.status==='Paid')return s.json({ok:true,ticketUrl:'/' });if(!verifyPaymentSignature(o.razorpay_order_id,razorpay_payment_id,razorpay_signature))return s.status(400).json({error:'Payment signature verification failed'});const payment=await fetchPayment(razorpay_payment_id);if(payment.order_id!==o.razorpay_order_id||payment.status!=='captured'||Number(payment.amount)!==Math.round(o.total*100))return s.status(400).json({error:'Payment is not captured or amount does not match'});const t=await markPaid(o.razorpay_order_id,razorpay_payment_id);s.json({ok:true,ticketUrl:t?'/ticket/'+t:'/orders?order='+o.id})}catch(e){console.error('Verify:',e.message);s.status(500).json({error:e.message||'Payment verification failed'})}});
app.get('/api/orders/:id',(q,s)=>{const id=cleanInt(q.params.id,1),email=String(q.query.email||'').trim();const o=db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o||!validEmail(email)||o.email.toLowerCase()!==email.toLowerCase())return s.status(404).json({error:'Order not found'});s.json({...o,items:orderItems(id),ticket:db.prepare('SELECT id,status,token FROM tickets WHERE order_id=? ORDER BY id DESC LIMIT 1').get(id)||null})});
app.get('/api/payment-status/:id',(q,s)=>{const id=cleanInt(q.params.id,1),email=String(q.query.email||'').trim(),o=db.prepare('SELECT id,email,status,razorpay_order_id FROM orders WHERE id=?').get(id);if(!o||o.email.toLowerCase()!==email.toLowerCase())return s.status(404).json({error:'Order not found'});s.json({id:o.id,status:o.status,razorpay_order_id:o.razorpay_order_id})});

app.get('/api/tickets/:token',(q,s)=>{const t=db.prepare('SELECT * FROM tickets WHERE token=?').get(q.params.token);if(!t)return s.status(404).json({error:'Ticket not found'});const messages=db.prepare('SELECT sender,message,created_at FROM messages WHERE ticket_id=? ORDER BY id').all(t.id),order=db.prepare('SELECT * FROM orders WHERE id=?').get(t.order_id);s.json({ticket:t,order,items:orderItems(t.order_id),messages})});
app.post('/api/tickets/:token/messages',(q,s)=>{const t=db.prepare('SELECT * FROM tickets WHERE token=?').get(q.params.token),m=String(q.body.message||'').trim();if(!t)return s.status(404).json({error:'Ticket not found'});if(!m||m.length>2000)return s.status(400).json({error:'Message must be 1–2000 characters'});db.prepare('INSERT INTO messages(ticket_id,sender,message) VALUES(?,?,?)').run(t.id,'customer',m);discord(`🎫 **Ticket #${t.id}**\n${m}`);s.json({ok:true})});
app.get('/api/admin/stats',admin,(q,s)=>{const stats=db.prepare(`SELECT COUNT(*) totalOrders,COALESCE(SUM(CASE WHEN status='Paid' THEN total ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN status NOT IN ('Paid','Payment Failed') THEN 1 ELSE 0 END),0) pendingOrders,(SELECT COUNT(*) FROM products) products,(SELECT COUNT(*) FROM tickets WHERE status!='Closed') openTickets FROM orders`).get();s.json(stats)});
app.get('/api/admin/orders',admin,(q,s)=>s.json(db.prepare(`SELECT o.*,GROUP_CONCAT(oi.product_name||' × '||oi.quantity, ', ') items FROM orders o LEFT JOIN order_items oi ON oi.order_id=o.id GROUP BY o.id ORDER BY o.id DESC LIMIT 100`).all()));
app.get('/api/admin/tickets',admin,(q,s)=>s.json(db.prepare('SELECT t.*,o.total,o.status order_status FROM tickets t JOIN orders o ON o.id=t.order_id ORDER BY t.id DESC').all()));
app.get('/api/admin/tickets/:id',admin,(q,s)=>{const id=cleanInt(q.params.id,1),t=db.prepare('SELECT * FROM tickets WHERE id=?').get(id);if(!t)return s.status(404).json({error:'Not found'});s.json({ticket:t,messages:db.prepare('SELECT * FROM messages WHERE ticket_id=? ORDER BY id').all(id)})});
app.post('/api/admin/tickets/:id/reply',admin,(q,s)=>{const m=String(q.body.message||'').trim();if(!m||m.length>2000)return s.status(400).json({error:'Message required'});db.prepare('INSERT INTO messages(ticket_id,sender,message) VALUES(?,?,?)').run(q.params.id,'admin',m);s.json({ok:true})});
app.post('/api/admin/tickets/:id/status',admin,(q,s)=>{const allowed=['Open','Processing','Completed','Closed'];if(!allowed.includes(q.body.status))return s.status(400).json({error:'Invalid status'});db.prepare('UPDATE tickets SET status=? WHERE id=?').run(q.body.status,q.params.id);s.json({ok:true})});
app.get('/admin',(q,s)=>s.sendFile(path.join(__dirname,'public/admin.html')));app.get('/orders',(q,s)=>s.sendFile(path.join(__dirname,'public/orders.html')));app.get('/ticket/:token',(q,s)=>s.sendFile(path.join(__dirname,'public/ticket.html')));
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:'Image upload failed: '+err.message});console.error(err);res.status(500).json({error:'Internal server error'})});
app.listen(PORT,()=>console.log(`Quick M@rt: http://localhost:${PORT}`));
